# Generated by Django 4.2.1 on 2023-08-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Category Name', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='upload/')),
            ],
            options={
                'db_table': 'tabcategory',
            },
        ),
    ]
