# Generated by Django 4.2.1 on 2023-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(max_length=11)),
                ('subcategory_name', models.CharField(help_text='Category Name', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='upload/')),
            ],
            options={
                'db_table': 'tabsubcategory',
            },
        ),
    ]
