# Generated by Django 4.0.10 on 2023-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(help_text='Subcategory Name', max_length=255),
        ),
    ]
