# Generated by Django 5.0.2 on 2024-05-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_post_blog_author_blog_main_post_blog_publish_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
