# Generated by Django 5.0.2 on 2024-05-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
