# Generated by Django 5.0.2 on 2024-05-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
