# Generated by Django 5.0.2 on 2024-05-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0014_ebook_purchased_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ebook',
        ),
    ]
