# Generated by Django 5.0.2 on 2024-05-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0016_ebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ebook',
        ),
    ]
